Jezz fix invite users
codersforcauses/p2s-frontend pull request #63
Opened 2019-02-01 08:57 UTC by JeremiahPinto

2019-02-05 02:38 UTC, fezproof commented
No description
What did you do?
What are the commits?
*I expect better*

2019-02-05 02:39 UTC, fezproof requested changes
*Tell me what you are trying to do*

2019-02-05 03:11 UTC, fezproof submitted a review, later dismissed

2019-02-05 03:11 UTC, fezproof commented on src/components/admin/StaffCard.vue
> +      this.finished = true;
What is this for?
Cant you do anything with the inbuilt booleans?

2019-02-05 03:11 UTC, fezproof commented on src/components/admin/StaffCard.vue
> -    <v-list v-show="!isFindPending" three-line subheader>
Remove all these changes, this is insane scope creeping
Please recreate changes in a seperate PR
*I expect better*

2019-02-05 14:19 UTC, JeremiahPinto commented on src/components/admin/StaffCard.vue
> +      this.finished = true;
The computed prop is called before the data is received which prints a from the getters which prints a bunch of console errors. This prevents that

2019-02-05 14:24 UTC, JeremiahPinto commented
The main reason for this PR was to fix a bug where the user could press the enter key without having permissions set and the response would still be sent. The other changes happened to be there coz i forgot to create a new branch

2019-02-11 02:57 UTC, fezproof approved these changes

2019-02-11 02:57 UTC, merged